### ISSUE TITLE
[Feature Request] Nuget Package

### ISSUE THREAD

**Issue by Nucs** [DysonCore/PolymorphicJson#1]
Very convenient implementation!
But I am lacking an easy install using nuget package.
Please add one.

Thanks!

**Comment by DysonCore** [comment]
NP. 
Will do in the next major version.

**Comment by DysonCore** [comment]
Unfortunately this implementation will remain UnityEngine specific, since new version uses file caching on Unity build events to not rely on heavy reflection for converter initialisation. 

Maybe later I will reuse parts of this package to create a nuget package, but It might be tricky to create a generic solution.
